import os
import io
import re
import asyncio
from typing import List, Dict, Any, Optional
from PIL import Image

import config
from intelligence.vision.models import VisionRequest, VisionResult, VisionImageItem
from intelligence.vision.task_classifier import VisualTask
from intelligence.vision.instruction_builder import build_vision_instruction
from tools.telemetry import log_structured, backend_log

class GeminiVisionProvider:
    """
    Gemini Multimodal Vision Provider (V3).
    Encapsulates single-pass multimodal visual reasoning using Google Generative AI SDK,
    incorporating task hint instructions, visual prompt injection defenses,
    evidence vs inference distinction, and bounded single-pass visual summaries.
    """

    def __init__(self):
        self.api_key = None
        self.model_name = None
        self.fallback_model_name = None
        self.initialized = False

    def _ensure_config(self) -> None:
        if not self.api_key or not self.model_name:
            self.api_key = (
                os.getenv("GEMINI_API_KEY") 
                or os.getenv("VITE_GEMINI_API_KEY") 
                or getattr(config, "GEMINI_API_KEY", None)
            )
            # Explicit primary model configuration
            configured_model = os.getenv("GEMINI_MODEL") or getattr(config, "GEMINI_MODEL", "gemini-2.5-flash")
            self.model_name = os.getenv("GEMINI_VISION_MODEL") or configured_model
            # Explicit optional fallback model configuration (No hardcoded silent fallback)
            self.fallback_model_name = os.getenv("GEMINI_VISION_FALLBACK_MODEL") or getattr(config, "GEMINI_VISION_FALLBACK_MODEL", None)

    def initialize(self) -> None:
        self._ensure_config()
        if not self.api_key:
            # Attempt to reload environment variables if newly written
            from config import backend_dir
            from dotenv import load_dotenv
            env_path = backend_dir / ".env"
            if env_path.exists():
                load_dotenv(dotenv_path=env_path, override=True)
            self.api_key = (
                os.getenv("GEMINI_API_KEY") 
                or os.getenv("VITE_GEMINI_API_KEY") 
                or getattr(config, "GEMINI_API_KEY", None)
            )

        if not self.api_key:
            raise ValueError("GEMINI_API_KEY is required for Vision Intelligence but is missing from configuration.")

        try:
            from google import genai
            self.client = genai.Client(api_key=self.api_key)
        except Exception:
            import google.generativeai as genai
            genai.configure(api_key=self.api_key)
            self.client = None

        self.initialized = True
        log_structured(backend_log, "INFO", f"[Vision] GeminiVisionProvider initialized with primary model '{self.model_name}' (Fallback: {self.fallback_model_name or 'None'})")

    def _extract_visual_summary(self, raw_text: str) -> tuple[str, Optional[str]]:
        """
        Single-pass extraction of bounded visual summary from response text.
        Returns (clean_user_text, bounded_visual_summary).
        """
        if not raw_text:
            return "No response generated by Vision model.", None

        # Look for [VISUAL SUMMARY: ...] at end of text
        summary_pattern = r"\[VISUAL SUMMARY:\s*(.*?)\]$"
        match = re.search(summary_pattern, raw_text, re.DOTALL | re.IGNORECASE)
        
        if match:
            summary_content = match.group(1).strip()
            # Bounded size, text-only, no binary/base64/paths
            clean_summary = re.sub(r"\s+", " ", summary_content)[:200]
            clean_user_text = raw_text[:match.start()].strip()
            return clean_user_text, clean_summary
        
        # Fallback bounded summary from first sentence/line without a second LLM call
        first_line = raw_text.strip().split("\n")[0]
        fallback_summary = re.sub(r"\s+", " ", first_line)[:200]
        return raw_text.strip(), fallback_summary

    async def analyze(self, request: VisionRequest) -> VisionResult:
        """
        Executes single-pass multimodal analysis on the provided images and prompt.
        """
        self._ensure_config()
        if not self.initialized:
            self.initialize()

        import google.generativeai as genai

        if not request.images or len(request.images) == 0:
            raise ValueError("At least one image is required for vision analysis.")

        # Resolve task enum hint
        task_str = request.task_type or "GENERAL_DESCRIPTION"
        task_enum = VisualTask(task_str) if task_str in VisualTask.__members__ else VisualTask.GENERAL_DESCRIPTION

        # Determine prompt or neutral instruction
        prompt_text = request.prompt.strip() if (request.prompt and request.prompt.strip()) else "Analyze this image and describe the important visual information."

        # Build task-specific system instruction
        system_instruction = build_vision_instruction(
            task_type=task_enum,
            user_prompt=prompt_text,
            image_count=len(request.images)
        )

        contents = [system_instruction + "\n\n"]

        # Include sanitized previous conversation context (untrusted text context)
        if request.conversation_context:
            context_lines = []
            for msg in request.conversation_context[-4:]:
                role = msg.get("role", "user")
                content = msg.get("content", "")
                if content:
                    context_lines.append(f"{role.capitalize()}: {content}")
            if context_lines:
                contents.append("Previous Conversation Context (Untrusted Data):\n" + "\n".join(context_lines) + "\n\n")

        # Convert raw image bytes to PIL Image objects safely
        pil_images = []
        for idx, img_item in enumerate(request.images, start=1):
            try:
                pil_img = Image.open(io.BytesIO(img_item.data))
                pil_images.append(pil_img)
            except Exception as e:
                raise ValueError(f"Failed to decode image '{img_item.filename}': {str(e)}")

        # Multi-image ordering and prompt assembly (Deterministic Image 1, Image 2, etc.)
        if len(pil_images) == 1:
            contents.append("Image 1:")
            contents.append(pil_images[0])
            contents.append(f"\nUser Request: {prompt_text}")
        else:
            contents.append(f"The user has provided {len(pil_images)} images. Analyze and compare them deterministically as requested.\n")
            for idx, img in enumerate(pil_images, start=1):
                contents.append(f"Image {idx}:")
                contents.append(img)
            contents.append(f"\nUser Request: {prompt_text}")

        # Execute Gemini multimodal inference asynchronously (Single pass)
        try:
            if getattr(self, "client", None) is not None:
                response = await asyncio.to_thread(self.client.models.generate_content, model=self.model_name, contents=contents)
            else:
                import google.generativeai as genai
                model = genai.GenerativeModel(model_name=self.model_name)
                response = await asyncio.to_thread(model.generate_content, contents)

            raw_text = response.text.strip() if (response and response.text) else ""

            user_text, summary_text = self._extract_visual_summary(raw_text)

            return VisionResult(
                text=user_text,
                provider="Gemini",
                model=self.model_name,
                image_count=len(request.images),
                task_type=task_enum.value,
                visual_summary=summary_text,
                uncertainty=False, # Natural observation-specific uncertainty in text
                metadata={"prompt_length": len(prompt_text), "task_hint": task_enum.value}
            )
        except Exception as e:
            err_msg = str(e)
            log_structured(backend_log, "ERROR", f"[Vision] Gemini Vision inference failed with model '{self.model_name}': {err_msg}")
            
            # Attempt retry ONLY if explicit fallback model is configured
            if self.fallback_model_name and self.model_name != self.fallback_model_name:
                log_structured(backend_log, "WARNING", f"[Vision] Retrying with explicitly configured fallback model '{self.fallback_model_name}'...")
                try:
                    if getattr(self, "client", None) is not None:
                        response = await asyncio.to_thread(self.client.models.generate_content, model=self.fallback_model_name, contents=contents)
                    else:
                        fallback_model = genai.GenerativeModel(model_name=self.fallback_model_name)
                        response = await asyncio.to_thread(fallback_model.generate_content, contents)

                    raw_text = response.text.strip() if (response and response.text) else ""
                    user_text, summary_text = self._extract_visual_summary(raw_text)

                    return VisionResult(
                        text=user_text,
                        provider="Gemini",
                        model=self.fallback_model_name,
                        image_count=len(request.images),
                        task_type=task_enum.value,
                        visual_summary=summary_text,
                        uncertainty=False,
                        metadata={"fallback": True, "fallback_model": self.fallback_model_name}
                    )
                except Exception as fb_err:
                    raise RuntimeError(f"Vision provider analysis failed with both primary '{self.model_name}' and fallback '{self.fallback_model_name}': {str(fb_err)}")

            raise RuntimeError(f"Vision provider analysis failed: {err_msg}")
