"""
Data models and enums for J.A.R.V.I.S. Intelligence I2.2 V3 — Multi-Source Research & Evidence Synthesis.
"""

from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from intelligence.web.models import GroundingStatus


class ResearchIntent(str, Enum):
    """Supported Research Intent Categories."""
    QUICK_FACT = "QUICK_FACT"
    CURRENT_EVENT = "CURRENT_EVENT"
    TECHNICAL_RESEARCH = "TECHNICAL_RESEARCH"
    PRODUCT_COMPARISON = "PRODUCT_COMPARISON"
    ACADEMIC_RESEARCH = "ACADEMIC_RESEARCH"
    FACT_CHECK = "FACT_CHECK"
    OFFICIAL_DOCUMENTATION = "OFFICIAL_DOCUMENTATION"
    NEWS_SYNTHESIS = "NEWS_SYNTHESIS"
    HISTORICAL_RESEARCH = "HISTORICAL_RESEARCH"
    MULTI_SOURCE_COMPARISON = "MULTI_SOURCE_COMPARISON"
    GENERAL_RESEARCH = "GENERAL_RESEARCH"
    NO_WEB = "NO_WEB"
    SIMPLE_LOOKUP = "SIMPLE_LOOKUP"


class FactCheckStatus(str, Enum):
    """Fact-checking claim evaluation states."""
    SUPPORTED = "SUPPORTED"
    MOSTLY_SUPPORTED = "MOSTLY_SUPPORTED"
    MISLEADING = "MISLEADING"
    UNSUPPORTED = "UNSUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class EvidenceRelationship(str, Enum):
    """Relationship between an evidence item and a research claim."""
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    PARTIALLY_SUPPORTS = "PARTIALLY_SUPPORTS"
    CONTEXT_ONLY = "CONTEXT_ONLY"
    UNKNOWN = "UNKNOWN"


class ResearchStatus(str, Enum):
    """Overall execution status of a research pipeline."""
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    SEARCH_FAILED = "SEARCH_FAILED"
    RETRIEVAL_FAILED = "RETRIEVAL_FAILED"
    TIMEOUT = "TIMEOUT"


class SourceSuitability(BaseModel):
    """Explainable non-numeric source suitability attributes."""
    domain: str
    is_primary_source: bool = False
    is_official: bool = False
    is_documentation: bool = False
    is_academic: bool = False
    is_news: bool = False
    matches_research_intent: bool = False
    reasons: List[str] = Field(default_factory=list)


class ResearchQuestion(BaseModel):
    """Sub-question generated by ResearchPlanner."""
    question_id: str
    query: str
    intent: ResearchIntent
    priority: int = 1
    is_verification_query: bool = False


class ResearchPlan(BaseModel):
    """Bounded multi-query research plan."""
    original_query: str
    primary_intent: ResearchIntent
    sub_questions: List[ResearchQuestion]
    max_rounds: int = 2
    max_sources: int = 5


class ResearchSource(BaseModel):
    """Verified research source entry."""
    source_id: str  # e.g., "source_1"
    url: str
    canonical_url: str
    domain: str
    title: str
    source_type: str
    suitability: SourceSuitability
    published_at: Optional[str] = None
    retrieved_at: str


class EvidenceItem(BaseModel):
    """Structured evidence item linked to source, sub-question, and canonical URL."""
    evidence_id: str  # e.g., "ev_1"
    source_id: str    # e.g., "source_1"
    canonical_url: str
    heading_path: List[str] = Field(default_factory=list)
    text: str
    sub_question_id: str
    relationship: EvidenceRelationship = EvidenceRelationship.UNKNOWN


class ResearchClaim(BaseModel):
    """Factual claim synthesized from evidence with complete evidence-to-source provenance chain."""
    claim_id: str
    statement: str
    supporting_evidence_ids: List[str] = Field(default_factory=list)
    contradicting_evidence_ids: List[str] = Field(default_factory=list)
    is_independent_confirmed: bool = False


class FactCheckDetail(BaseModel):
    """Detailed breakdown for FACT_CHECK intent preserving qualifiers."""
    user_claim: str
    qualifiers: List[str] = Field(default_factory=list)       # e.g., ["free-threaded build", "optional flag"]
    version_scope: Optional[str] = None                       # e.g., "Python 3.14"
    verdict: FactCheckStatus = FactCheckStatus.INSUFFICIENT_EVIDENCE
    explanation: str = ""


class ResearchConflict(BaseModel):
    """Explicitly identified conflict between sources."""
    conflict_id: str
    topic: str
    claim_a: str
    evidence_a_id: str
    source_a_id: str
    claim_b: str
    evidence_b_id: str
    source_b_id: str
    resolution_status: str  # "UNRESOLVED", "RESOLVED_PRIMARY_PREFERENCE", "RESOLVED_NEWER_DATE"
    explanation: str


class ResearchFinding(BaseModel):
    """Synthesized research summary."""
    summary: str
    claims: List[ResearchClaim] = Field(default_factory=list)
    conflicts: List[ResearchConflict] = Field(default_factory=list)
    fact_check_detail: Optional[FactCheckDetail] = None


class ResearchRequest(BaseModel):
    """API request model for deep web research."""
    query: str
    force_research: bool = False
    max_sources: int = 5
    max_rounds: int = 2
    conversation_id: Optional[str] = None


class ResearchResponse(BaseModel):
    """Complete research response payload."""
    query: str
    intent: ResearchIntent
    status: ResearchStatus
    plan: Optional[ResearchPlan] = None
    sources: List[ResearchSource] = Field(default_factory=list)
    evidence_items: List[EvidenceItem] = Field(default_factory=list)
    finding: Optional[ResearchFinding] = None
    grounding_status: GroundingStatus = GroundingStatus.FULL_PAGE_RETRIEVED
    latency_ms: float = 0.0
    error: Optional[str] = None
