"""
Event payload definitions for J.A.R.V.I.S. Phase V1.4 Voice Output Engine (TTS).
All events carry explicit playback_id, timestamps, and session metadata.
"""
import time
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class SpeechSynthesisStarted:
    """Emitted when TTS synthesis commences for a text utterance."""
    playback_id: str
    turn_id: Optional[str] = None
    text: str = ""
    voice_id: str = "default"
    provider: str = "mock"
    timestamp: float = field(default_factory=time.time)


@dataclass
class SpeechChunkGenerated:
    """Emitted when a new audio chunk is generated by the TTS provider."""
    playback_id: str
    chunk_id: str
    chunk_index: int
    is_final: bool = False
    latency_ms: float = 0.0
    timestamp: float = field(default_factory=time.time)


@dataclass
class SpeechPlaybackStarted:
    """Emitted when audio playback begins on the output driver."""
    playback_id: str
    voice_id: str
    timestamp: float = field(default_factory=time.time)


@dataclass
class SpeechPlaybackPaused:
    """Emitted when audio playback is paused."""
    playback_id: str
    timestamp: float = field(default_factory=time.time)


@dataclass
class SpeechPlaybackResumed:
    """Emitted when audio playback is resumed."""
    playback_id: str
    timestamp: float = field(default_factory=time.time)


@dataclass
class SpeechPlaybackCompleted:
    """Emitted when audio playback completes cleanly."""
    playback_id: str
    audio_duration_ms: float = 0.0
    total_chunks: int = 0
    timestamp: float = field(default_factory=time.time)


@dataclass
class SpeechPlaybackCancelled:
    """Emitted when audio playback is cancelled or interrupted."""
    playback_id: str
    reason: str = "user_cancellation"
    timestamp: float = field(default_factory=time.time)


@dataclass
class SpeechPlaybackError:
    """Emitted when an error occurs during synthesis or audio output playback."""
    playback_id: str
    error_type: str
    message: str
    timestamp: float = field(default_factory=time.time)
