"""
J.A.R.V.I.S. Product Layer (Phase P1.1) Package Initialization.
Exports Identity & User Management domain models, roles, security audit logging, interfaces, services, and public engine APIs.
"""
from .config import ProductConfig, product_config
from .models import (
    User,
    Role,
    AccountStatus,
    UserProfile,
    UserPreferences,
    VoiceSettings,
    NotificationSettings,
    PrivacySettings,
    Session,
    PasswordResetToken,
    AuthResult,
    SecurityContext,
)
from .interfaces import (
    IUserRepository,
    IProfileRepository,
    ISessionRepository,
    IPreferenceRepository,
    IPasswordResetRepository,
    IAuditRepository,
    IPasswordHasher,
    ITokenGenerator,
    ISecurityProvider,
)
from .security import (
    PasswordHasher,
    TokenGenerator,
    InputValidator,
    SlidingWindowRateLimiter,
    SecurityProvider,
    security_provider,
)
from .audit import (
    AuditLevel,
    AuditEvent,
    AuditEntry,
    SecurityAuditLogger,
)
from .storage import SQLiteProductStorage
from .users import UserManager
from .profiles import ProfileManager
from .sessions import SessionManager
from .preferences import PreferenceManager
from .authentication import AuthenticationService
from .coordinator import ProductCoordinator
from .engine import ProductEngine, product_engine
from .plugins import (
    ProductPluginManager,
    plugin_manager_instance,
    PluginState,
    PluginStatus,
    PluginManifest,
    PluginPermissionScope,
    PermissionConsentStatus,
    PluginCategory,
    SkillDefinition,
    CommandDefinition,
    PluginValidator,
    PluginPermissionEngine,
    PluginConfigEngine,
    PluginAPIContext,
    PluginLifecycleManager,
    PluginIsolationGuard,
)
from .tools import (
    ProductToolExecutionManager,
    tool_execution_manager_instance,
    ToolMetadata,
    ExecutionContext,
    ToolExecutionResult,
    ExecutionStatusCode,
    ExecutionMetrics,
    RetryPolicy,
    ToolCapability,
    ToolCategory,
)
from .knowledge import (
    KnowledgeManager,
    knowledge_manager_instance,
    DocumentManager,
    Document,
    DocumentStatus,
    DocumentType,
    DocumentPermissions,
    Chunk,
    ChunkLocation,
    SQLiteVectorStore,
    SQLiteMetadataStore,
    HybridSearchEngine,
    RetrievalPipeline,
    RAGCoordinator,
)
from .automation import (
    AutomationManager,
    automation_manager_instance,
    WorkflowManager,
    Workflow,
    WorkflowStatus,
    TriggerType,
    TriggerConfig,
    ConditionConfig,
    ActionStep,
    WorkflowRunRecord,
    AutomationScheduler,
)
from .integrations import (
    WorkspaceIntegrationManager,
    workspace_integration_manager_instance,
    WorkspaceConnector,
    AuthType as IntegrationAuthType,
    ConnectorStatus,
    CircuitState,
    SecretHandle,
    ProviderCapabilities,
)
from .voice import (
    VoiceEngine,
    voice_engine_instance,
    VoiceSessionManager,
    VoiceSession,
    VoiceSessionState,
    ConversationTurn,
    VoiceNotification,
    NotificationPriority,
    IntentCategory,
)

__all__ = [
    "ProductConfig",
    "product_config",
    "User",
    "Role",
    "AccountStatus",
    "UserProfile",
    "UserPreferences",
    "VoiceSettings",
    "NotificationSettings",
    "PrivacySettings",
    "Session",
    "PasswordResetToken",
    "AuthResult",
    "SecurityContext",
    "IUserRepository",
    "IProfileRepository",
    "ISessionRepository",
    "IPreferenceRepository",
    "IPasswordResetRepository",
    "IAuditRepository",
    "IPasswordHasher",
    "ITokenGenerator",
    "ISecurityProvider",
    "PasswordHasher",
    "TokenGenerator",
    "InputValidator",
    "SlidingWindowRateLimiter",
    "SecurityProvider",
    "security_provider",
    "AuditLevel",
    "AuditEvent",
    "AuditEntry",
    "SecurityAuditLogger",
    "SQLiteProductStorage",
    "UserManager",
    "ProfileManager",
    "SessionManager",
    "PreferenceManager",
    "AuthenticationService",
    "ProductCoordinator",
    "ProductEngine",
    "product_engine",
    "ProductPluginManager",
    "plugin_manager_instance",
    "PluginState",
    "PluginStatus",
    "PluginManifest",
    "PluginPermissionScope",
    "PermissionConsentStatus",
    "PluginCategory",
    "SkillDefinition",
    "CommandDefinition",
    "PluginValidator",
    "PluginPermissionEngine",
    "PluginConfigEngine",
    "PluginAPIContext",
    "PluginLifecycleManager",
    "PluginIsolationGuard",
    "ProductToolExecutionManager",
    "tool_execution_manager_instance",
    "ToolMetadata",
    "ExecutionContext",
    "ToolExecutionResult",
    "ExecutionStatusCode",
    "ExecutionMetrics",
    "RetryPolicy",
    "ToolCapability",
    "ToolCategory",
    "KnowledgeManager",
    "knowledge_manager_instance",
    "DocumentManager",
    "Document",
    "DocumentStatus",
    "DocumentType",
    "DocumentPermissions",
    "Chunk",
    "ChunkLocation",
    "SQLiteVectorStore",
    "SQLiteMetadataStore",
    "HybridSearchEngine",
    "RetrievalPipeline",
    "RAGCoordinator",
    "AutomationManager",
    "automation_manager_instance",
    "WorkflowManager",
    "Workflow",
    "WorkflowStatus",
    "TriggerType",
    "TriggerConfig",
    "ConditionConfig",
    "ActionStep",
    "WorkflowRunRecord",
    "AutomationScheduler",
    "WorkspaceIntegrationManager",
    "workspace_integration_manager_instance",
    "WorkspaceConnector",
    "IntegrationAuthType",
    "ConnectorStatus",
    "CircuitState",
    "SecretHandle",
    "ProviderCapabilities",
    "VoiceEngine",
    "voice_engine_instance",
    "VoiceSessionManager",
    "VoiceSession",
    "VoiceSessionState",
    "ConversationTurn",
    "VoiceNotification",
    "NotificationPriority",
    "IntentCategory",
]



